#!/bin/bash

docker volume create portainer_data
docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest

echo 
echo
echo -e "\tEntra en https://localhost:9443 e inicia la configuración ..."
echo
echo
