version: "3.8"

services:
  nagios:
    image: jasonrivers/nagios:latest
    container_name: nagios
    restart: unless-stopped

    ports:
      - "8080:80"

    environment:
      - NAGIOSADMIN_USER=nagiosadmin
      - NAGIOSADMIN_PASS=nagiosadmin

    volumes:
      # Configuración de Nagios
      - ./fs/etc:/opt/nagios/etc

      # Datos de estado, logs, etc
      - ./fs/var:/opt/nagios/var

      # Plugins personalizados
      - ./fs/plugins:/opt/Custom-Nagios-Plugins

    networks:
      - nagios-net

networks:
  nagios-net:
    driver: bridge

